import os
import shutil
import time, datetime
import tabulate

import subprocess

times = []
tests = [
    "test0", "test1", "test2", "test3", "test4", "test5", "test6", "test7", 
    "test9",  "test10", "test11", "test12", "test13", "test14", "test15"
]

test_dir = f"{os.getcwd()}/riscv-sodor-model/verification/sodor_security/"

dut_dir = "sec_taskBMC20_sodor5_lb_u"
mod_dir = "sec_taskBMC20_sodor5_model_lb_u"

for test in tests:
    print("Running test: " + test)
    shutil.copyfile(f"{test_dir}/{test}/sodor5_lb_unified_bmc.v", f"{test_dir}/sodor5_lb_unified_bmc.v")
    
    # Test with design
    pretime = time.time()
    subprocess.Popen(['time', 'sby', '-f', 'sec.sby', 'taskBMC20_sodor5_lb_u'], cwd=test_dir).wait()
    posttime = time.time()
    dut_time = posttime - pretime
    print(f"For test: {test} DUT time: {dut_time}")

    # Save the results
    os.system(f"cp -r {test_dir}/{dut_dir} {test_dir}/{test}")

    # Test on model
    pretime = time.time()
    subprocess.Popen(['time', 'sby', '-f', 'sec.sby', 'taskBMC20_sodor5_model_lb_u'], cwd=test_dir).wait()
    posttime = time.time()
    model_time = posttime - pretime
    print(f"For test: {test} Model time: {model_time}")

    # Save the results
    os.system(f"cp -r {test_dir}/{mod_dir} {test_dir}/{test}")

    # Save the times
    times.append([
        test, dut_time, model_time
    ])



with open("sodor5_sec_times.log", 'w') as f:
    f.write("// Generated by sodor5_security_script.py at {}\n\n\n".format(datetime.datetime.now()))

    table = tabulate.tabulate(times, headers=["Test", "Design Runtime (s)", "Model Runtime (s)"])
    f.write(table)